version: "2"
services:
  sender:
    build: ./sender
    environment:
      RECEIVE_HOST: dockerbridge.thisdoesnotexist.io
  receiver:
    build: ./receiver
  haproxy:
    image: haproxy:1.8
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
#    networks:
#      default:
#        aliases:
#          - dockerbridge.thisdoesnotexist.io
