version: "2"
services:
  sender:
    build: ./sender
    environment:
      RECEIVE_HOST: dockerbridge.thisdoesnotexist.io
  receiver:
    build: ./receiver
  haproxy:
    build: ./haproxy
    ports:
      - "80:80"
    depends_on:
      - receiver
    networks:
      default:
        aliases:
          - dockerbridge.thisdoesnotexist.io
