version: "2"
networks:
  balena:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
services:
  sender:
    build: ./sender
    environment:
      RECEIVE_HOST: 192.168.1.169
    networks:
      balena:
        ipv4_address: 172.25.0.10
  receiver:
    build: ./receiver
    networks:
      balena:
        ipv4_address: 172.25.0.20
  haproxy:
    network_mode: "host"
    image: haproxy:1.8
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    depends_on:
      - receiver

